name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: false
        default: ''
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.GO_REST_HOST }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run api

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: monocart-report
        path: monocart-report/
        retention-days: 30
